import { demoDeliverables } from '../data/demo';
import { cn, formatBytes, formatRelativeTime } from '../utils';
import { FileText, Code2, Download, CheckCircle2, Clock, User, Bot } from 'lucide-react';

const typeIcon: Record<string, React.ReactNode> = {
  docx: <FileText size={16} className="text-accent-blue" />,
  xlsx: <FileText size={16} className="text-accent-green" />,
  code: <Code2 size={16} className="text-accent-purple" />,
  report: <FileText size={16} className="text-brand-400" />,
};

export default function Deliverables() {
  return (
    <div className="space-y-5 animate-slide-in">
      <div className="grid grid-cols-4 gap-4">
        {[
          { label: 'Total', value: demoDeliverables.length, color: 'text-slate-100' },
          { label: 'Human Approved', value: demoDeliverables.filter(d => d.isHumanApproved).length, color: 'text-accent-green' },
          { label: 'Pending Approval', value: demoDeliverables.filter(d => !d.isHumanApproved).length, color: 'text-accent-amber' },
          { label: 'Validated', value: demoDeliverables.filter(d => d.validationStatus === 'pass').length, color: 'text-brand-400' },
        ].map(s => (
          <div key={s.label} className="card-sm text-center">
            <p className={cn('text-2xl font-bold', s.color)}>{s.value}</p>
            <p className="text-[11px] text-slate-500 mt-0.5">{s.label}</p>
          </div>
        ))}
      </div>

      <div className="space-y-3">
        {demoDeliverables.map(d => (
          <div key={d.id} className="card">
            <div className="flex items-start gap-4">
              <div className="mt-1">{typeIcon[d.deliverableType] || typeIcon.report}</div>
              <div className="flex-1 min-w-0">
                <p className="text-sm font-semibold text-slate-200 mb-1">{d.filename}</p>
                <p className="text-xs text-slate-500 mb-2">{d.taskTitle}</p>
                <div className="flex items-center gap-3 flex-wrap">
                  <span className={cn('badge text-[10px]', d.validationStatus === 'pass' ? 'badge-green' : 'badge-amber')}>
                    Validation {d.validationStatus.toUpperCase()}
                  </span>
                  <span className="flex items-center gap-1 text-[10px] text-slate-500">
                    <Bot size={10} /> AI Generated
                  </span>
                  {d.isHumanApproved && (
                    <span className="flex items-center gap-1 text-[10px] text-accent-green">
                      <User size={10} /> Human Approved
                    </span>
                  )}
                  {!d.isHumanApproved && (
                    <span className="flex items-center gap-1 text-[10px] text-accent-amber">
                      <Clock size={10} /> Pending Approval
                    </span>
                  )}
                  {d.fileSizeBytes && <span className="text-[10px] text-slate-600">{formatBytes(d.fileSizeBytes)}</span>}
                </div>
                {d.validationNotes && <p className="text-[11px] text-slate-500 mt-2">{d.validationNotes}</p>}
              </div>
              <div className="flex flex-col items-end gap-2 flex-shrink-0">
                <span className="text-[10px] text-slate-500">{formatRelativeTime(d.createdAt)}</span>
                <button className="btn btn-secondary text-xs py-1">
                  <Download size={12} /> Download
                </button>
              </div>
            </div>
          </div>
        ))}
      </div>
      <p className="text-[11px] text-slate-600 text-center">
        [DEMO DATA — Real files generated by backend Work-Product Engine]
      </p>
    </div>
  );
}
